'use client';
import {useState} from 'react';
import {Activity, Gauge, Link2, RefreshCw, ShieldCheck, WalletCards} from 'lucide-react';
import {useLedger} from '@/lib/ledger';
import deployment from '@/artifacts/deployment.json';

type Source={url:string;path:string};
const initial:Source[]=[{url:'https://api.example.com/quote-a',path:'price'},{url:'https://api.example.net/quote-b',path:'price'},{url:'https://api.example.org/quote-c',path:'price'}];
export default function Home(){const l=useLedger(deployment.address);const[id,setId]=useState('BTC-USD');const[bound,setBound]=useState('500');const[sources,setSources]=useState(initial);const[lookup,setLookup]=useState('BTC-USD');const[record,setRecord]=useState<any>(null);
 const set=(i:number,k:keyof Source,v:string)=>setSources(s=>s.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function register(){const body=JSON.stringify(sources.map(s=>({url:s.url,path:s.path.split('.').filter(Boolean)})));await l.write('register_feed',[id,body,Number(bound)],async()=>true)}
 async function sample(){await l.write('sample_feed',[id],async()=>{const r=await l.read('get_feed',[l.account,id]);setRecord(r);return r?.id===id.toUpperCase()})}
 async function read(){try{setRecord(await l.read('get_feed',[l.account,lookup]))}catch{setRecord(null)}}
 return <main><header><div className="brand"><span className="pulse"><Activity/></span><div><b>QuoteQuorum</b><small>BOUNDED MARKET SNAPSHOTS</small></div></div><div className="network"><i/> STUDIONET</div><button className="wallet" onClick={l.connect}><WalletCards size={16}/>{l.account?l.account.slice(0,6)+'…'+l.account.slice(-4):'Connect wallet'}</button></header><section className="hero"><div><p className="eyebrow">PRICE DISCOVERY / DISPERSION GUARD</p><h1>Three quotes.<br/><em>One honest range.</em></h1><p className="intro">QuoteQuorum turns live JSON prices into a bounded market snapshot. Validators independently fetch three to five providers, normalize the values, and flag dispersion instead of trusting one oracle.</p></div><div className="gauge"><Gauge/><strong>≤ {bound} BPS</strong><small>maximum permitted spread</small></div></section><section className="panel"><div className="panel-head"><span>01 / FEED REGISTRATION</span><h2>Compose a quote quorum</h2><p>Every provider must use a distinct hostname. JSON paths point to the numeric quote.</p></div><div className="controls"><label>FEED ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>SPREAD BOUND (BPS)<input type="number" value={bound} onChange={e=>setBound(e.target.value)}/></label></div><div className="sources">{sources.map((s,i)=><div className="source" key={i}><span className="index">0{i+1}</span><Link2/><label>PROVIDER URL<input value={s.url} onChange={e=>set(i,'url',e.target.value)}/></label><label>JSON PATH<input value={s.path} onChange={e=>set(i,'path',e.target.value)}/></label></div>)}</div><div className="actions"><button onClick={register} disabled={!l.account||l.busy}>Register feed <span>→</span></button><button onClick={sample} disabled={!l.account||l.busy}>Sample with consensus <RefreshCw size={16}/></button></div><p className="status">{l.message||'Connect your wallet to register an owner-scoped feed.'}</p></section><section className="readback"><div><p className="eyebrow">PUBLIC READBACK</p><h2>Inspect a snapshot</h2><p>Look up a feed by owner and ID after finalization.</p></div><div className="lookup"><input value={lookup} onChange={e=>setLookup(e.target.value)}/><button onClick={read}>Read feed</button></div>{record?.id&&<div className="result"><div className="result-main"><ShieldCheck/><small>LATEST STATUS</small><strong>{record.status}</strong><p>Median {record.median} · spread {Number(record.spread_bps).toFixed(1)} bps</p></div>{(record.quotes||[]).map((q:number,i:number)=><div className="quote" key={i}><span>PROVIDER 0{i+1}</span><b>{q}</b><small>{record.digests?.[i]?.slice(0,18)}…</small></div>)}</div>}</section><footer>QuoteQuorum · validator-fetched prices · bounded dispersion · {deployment.address.slice(0,10)}…</footer></main>}
